### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by SettingDust** [MerchantPug/bovines-and-buttercups#19]
```
[11:55:39] [Render thread/ERROR] (Minecraft) Unhandled game exception
org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'jei_mod_plugin' provided by 'bovinesandbuttercups'
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:225) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:54) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:34) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at mezz.jei.fabric.startup.FabricPluginFinder.getInstances(FabricPluginFinder.java:25) ~[transformed-mod-jei.i0:0/:?]
	at mezz.jei.fabric.startup.FabricPluginFinder.getModPlugins(FabricPluginFinder.java:16) ~[transformed-mod-jei.i0:0/:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.<init>(ClientLifecycleHandler.java:40) ~[transformed-mod-jei.i0:0/:?]
	at mezz.jei.fabric.JustEnoughItemsClient.lambda$onInitializeClient$0(JustEnoughItemsClient.java:28) ~[transformed-mod-jei.i0:0/:?]
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:45) ~[transformed-mod-quilt-lifecycle-events.i0:0/:?]
	at net.minecraft.class_310.handler$dlf000$quilt_lifecycle_events$clientReady(class_310.java:19476) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [transformed-mod-minecraft-v1.19.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) [quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.19.2-beta.2.jar:?]
Caused by: org.quiltmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.merchantpug.bovinesandbuttercups.client.integration.jei.BovinesJeiPlugin
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:115) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:223) ~[quilt-loader-0.19.2-beta.2.jar:?]
	... 25 more
Caused by: java.lang.ClassNotFoundException: net.merchantpug.bovinesandbuttercups.client.integration.jei.BovinesJeiPlugin
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:115) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:223) ~[quilt-loader-0.19.2-beta.2.jar:?]
	... 25 more
```

**Comment by ChrysanthCow** [comment]
Thanks for this report, I'll get to fixing it sometime.

**Comment by ChrysanthCow** [comment]
Fixed in release v1.6.2.1 (1.6.2.0 doesn't exist due a mistake)

**Comment by SettingDust** [comment]
1.6.2.1+1.19.2-quilt
```
Caused by: org.quiltmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.merchantpug.bovinesandbuttercups.integration.jei.BovinesJeiPlugin
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:115) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:223) ~[quilt-loader-0.19.2-beta.2.jar:?]
	... 25 more
Caused by: java.lang.ClassNotFoundException: net.merchantpug.bovinesandbuttercups.integration.jei.BovinesJeiPlugin
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:115) ~[quilt-loader-0.19.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:223) ~[quilt-loader-0.19.2-beta.2.jar:?]
	... 25 more
```

**Comment by SettingDust** [comment]
![图片](https://github.com/MerchantPug/bovines-and-buttercups/assets/19922286/7479fb9f-0b0d-45f1-b7fe-89a5d131d50b)

**Comment by SettingDust** [comment]
Should be `BovineJeiPlugin` instead of `BovinesJeiPlugin`. There is an extra `s`

**Comment by tamasys** [comment]
@MerchantPug I'm still getting this error with JEI (Minecraft v1.19.2, Quilt v0.20.0-beta.11, B&B v1.6.2.1, JEI v11.6.0.1016) - I assume because of @SettingDust's comments above?

**Comment by ChrysanthCow** [comment]
I guess I'll push another fix sometime later, sorry for not realising that it wasn't fixed.

**Comment by ChrysanthCow** [comment]
> Should be `BovineJeiPlugin` instead of `BovinesJeiPlugin`. There is an extra `s`

That'd do it, my bad.

**Comment by ChrysanthCow** [comment]
Hi, sorry for the wait. My release scripts were acting up due to differences between the past and now.
